### ISSUE TITLE
Building against libcblas-3.8.0-13_openblas fails due to moved cblas.h

### ISSUE THREAD

**Issue by fhoehle** [conda-forge/scikit-learn-feedstock#103]
I'm trying to build this package with a slightly different variant file using openblas' instead netlib's `libcblas`. The build process is failing due to the required removing of `cblas.h` by the build script https://github.com/conda-forge/scikit-learn-feedstock/blob/master/recipe/meta.yaml#L16 .

Minimal example:

```shell
foo@bar:~/scikit-learn-feedstock$ sed 's/netlib/openblas/g' .ci_support/linux_python3.7.yaml > .ci_support/linux_python3.7_openblas.yaml
foo@bar:~/scikit-learn-feedstock$ diff -u .ci_support/linux_python3.7.yaml .ci_support/linux_python3.7_openblas.yaml 
--- .ci_support/linux_python3.7.yaml	2019-10-08 10:35:55.000000000 +0200
+++ .ci_support/linux_python3.7_openblas.yaml	2019-10-08 10:37:28.000000000 +0200
@@ -13,7 +13,7 @@
 docker_image:
 - condaforge/linux-anvil-comp7
 libcblas:
-- 3.8 *netlib
+- 3.8 *openblas
 numpy:
 - '1.14'
 pin_run_as_build:
foo@bar:~/scikit-learn-feedstock$ ./build-locally.py linux_python3.7_openblas
...
INFO: activate-gxx_linux-64.sh made the following environmental changes:
+CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/scikit-learn-0.21.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+CXX=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++
+DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/scikit-learn-0.21.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+GXX=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-g++
rm: cannot remove `/home/conda/feedstock_root/build_artifacts/scikit-learn_1570524327711/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/cblas.h': No such file or directory
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2343, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1491, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 397, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 377, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/conda/feedstock_root/build_artifacts/scikit-learn_1570524327711/work/conda_build.sh']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "./build-locally.py", line 58, in <module>
    main()
  File "./build-locally.py", line 54, in main
    run_docker_build(ns)
  File "./build-locally.py", line 19, in run_docker_build
    subprocess.check_call(script)
  File "/Users/felixhoehle/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '.azure-pipelines/run_docker_build.sh' returned non-zero exit status 1.
```

**Comment by isuruf** [comment]
What's the reason to try building with openblas instead of netlib?

**Comment by jakirkham** [comment]
I don’t think that is needed. What would you propose we change?

**Comment by rth** [comment]
Sorry, closing as no response in a while, and I'm not sure why we would need it. Scikit-learn now uses blas only via scipy, and so it shouldn't need `cblas.h` in any case.
