### ISSUE TITLE
Unsatisfiable dependencies for platform linux-64 (gcc7)

### ISSUE THREAD

**Issue by ogrisel** [conda-forge/scikit-learn-feedstock#88]
One of the build on master resulting from the merge of the 0.20.2 feedstock PR failed with the following "Unsatisfiable dependencies for platform linux-64" error:

[build_linux_c_compilergcccxx_compilergxxpython3.6](https://circleci.com/gh/conda-forge/scikit-learn-feedstock/940) (gcc7)

```
####################################################################################
Source and build intermediates have been left in /home/conda/feedstock_root/build_artifacts.
There are currently 1 accumulated.
To remove them, you can run the ```conda build purge``` command
+ upload_package /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_c_compilergcccxx_compilergxxpython3.6.yaml
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
Adding in variants from /home/conda/feedstock_root/.ci_support/linux_c_compilergcccxx_compilergxxpython3.6.yaml
Solving environment: ...working... failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda_build/environ.py", line 753, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/opt/conda/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.6/site-packages/conda/plan.py", line 541, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
    force_remove, force_reinstall)
  File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 451, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 331, in solve_final_state
    conflicting_specs = r.get_conflicting_specs(tuple(final_environment_specs))
  File "/opt/conda/lib/python3.6/site-packages/conda/resolve.py", line 746, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "/opt/conda/lib/python3.6/site-packages/conda/resolve.py", line 254, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/opt/conda/lib/python3.6/site-packages/conda/resolve.py", line 172, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - blas==1.1=openblas
  - openblas
  - libgfortran-ng[version='>=7,<8.0a0']
  - scipy
  - blas==1.1=openblas
  - openblas
  - libgfortran-ng[version='>=7,<8.0a0']
  - scipy
  - numpy[version='>=1.9.3,<2.0a0']
  - *[track_features=blas_openblas]
  - openblas=0.3.3
  - libgfortran-ng[version='>=7,<8.0a0']
  - numpy=1.9
  - blas==1.1=openblas
  - openblas
  - libgfortran-ng[version='>=7,<8.0a0']
  - numpy=1.9
  - *[track_features=blas_openblas]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/upload_package", line 11, in <module>
    sys.exit(upload_package())
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/build_utils.py", line 82, in upload_package
    upload_or_check(recipe_root, owner, channel, [config_file])
  File "/opt/conda/lib/python3.6/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 106, in upload_or_check
    recipe_dir, variant_config_files=variant, **additional_config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 44, in render
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 809, in render_recipe
    allow_no_other_outputs=True, bypass_env_check=bypass_env_check)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 714, in distribute_variants
    bypass_env_check=bypass_env_check)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/metadata.py", line 1014, in parse_until_resolved
    bypass_env_check=bypass_env_check)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/metadata.py", line 936, in parse_again
    bypass_env_check=bypass_env_check),
  File "/opt/conda/lib/python3.6/site-packages/conda_build/metadata.py", line 1523, in _get_contents
    rendered = template.render(environment=env)
  File "/opt/conda/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/conda/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/conda/recipe_root/meta.yaml", line 38, in top-level template code
    - blas 1.1 {{ variant }}
  File "/opt/conda/lib/python3.6/site-packages/conda_build/jinja_context.py", line 230, in pin_compatible
    pins, _, _ = get_env_dependencies(m, 'host', m.config.variant)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 143, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/opt/conda/lib/python3.6/site-packages/conda_build/environ.py", line 755, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"numpy[version='>=1.9.3,<2.0a0']", '*[track_features=blas_openblas]', 'scipy', 'blas==1.1=openblas', 'numpy=1.9', 'openblas=0.3.3', "libgfortran-ng[version='>=7,<8.0a0']", 'openblas'}
Exited with code 1
```

Why didn't we get the issue on the PR #87?

**Comment by ogrisel** [comment]
Apparently the result is that the linux py36 package for scikit-learn 0.20.2 with build number 1400 is missing from the conda-forge channel:

https://anaconda.org/conda-forge/scikit-learn/files

But I am not sure how the build number /  compiler things work together.

**Comment by ocefpaf** [comment]
It is odd that it passed on the PR but failed on master :-/
Looking into it...

**Comment by ocefpaf** [comment]
Looks like just restarting the CIs fixed it.

**Comment by ogrisel** [comment]
Thanks @ocefpaf!
